#!/usr/bin/env bash

scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

configFile=$scriptDir/slash.conf
verbose=false

json_parser=$scriptDir/vendor/jq
man_viewer=$scriptDir/vendor/mad

function usage() {
cat << EOF
    usage: $0 [-h] [-v] [-f configFile] reference[:type[,type]...][:docset[,docset]...]
EOF
}

function bad_syntax() {
cat << EOF
    Bad syntax for reference, should be:

        reference[:type][:docset]

EOF
}

function process_args() {
    while getopts "f:hv" OPTION
    do
        case $OPTION in
            h)
                usage
                exit 1
                ;;
            f)
                configFile=$OPTARG
                ;;
            v)
                verbose=1
                ;;
            ?)
                usage
                exit
                ;;
        esac
    done
    
    shift $(($OPTIND-1))
    if [[ $# != 1 ]]
    then
        usage
        exit
    fi
}

get() {
    grep "$1" "$configFile" | awk '{ print $2 }'
}

split() {
    parts=($(echo "$1" | tr "$2" " "))
}

function get_query() {
    split $1 ":"

    num_parts=${#parts[@]}
    if [ $num_parts -lt 1 ] || [ $num_parts -gt 3 ]
    then
        bad_syntax
        exit 1
    fi

    reference=${parts[0]}
    types=${parts[1]}
    docsets=${parts[2]}

    local server=$(get server)
    local port=$(get port)

    local url="http://${server}:${port}/search?reference=${reference}"

    split $types ","
    for type in ${parts[@]}
    do
        if [[ $type != "," ]]
        then
            url="${url}&types=${type}"
        fi
    done

    split $docsets ","
    for docset in ${parts[@]}
    do
        if [[ $docset != "," ]]
        then
            url="${url}&docsets=${docset}"
        fi
    done

    query_url=$url
}

function show_results() {
    results=$1
    numResults=$(echo $results | $json_parser '. | length')
    if [[ "$numResults" == "1" ]]
    then
        server=$(get server)
        port=$(get port)
        url=$(echo $results | $json_parser '@uri "http://'${server}':'${port}'/get/\(.[0].docset)/\(.[0].type)/\(.[0].reference)"' | cut -d "\"" -f 2)
        content=$(curl -s ${url} | $json_parser '.content' | cut -d "\"" -f 2)
        echo -e $content | $man_viewer -
    else
        dialog_options=""
        num=0
        width=25
        references=$(echo $results | $json_parser '.[] | "\(.reference):\(.type):\(.docset)"')
        for result in $references
        do
            num=$(expr $num + 1)
            option=$(echo $result | cut -d "\"" -f 2)
            ref=$(echo $option | awk 'BEGIN {FS=":"} {print $1}')
            type=$(echo $option | awk 'BEGIN {FS=":"} {print $2}')
            docset=$(echo $option | awk 'BEGIN {FS=":"} {print $3}')
            text="$ref($type) in $docset"
            len=$(echo $text | wc -c)
            if [ $len -gt $width ]
            then
                width=$len
            fi
            dialog_options="$dialog_options $num \"$text\""
        done
        width=$(expr $width + 10)
        selection=$(echo $dialog_options | xargs dialog --begin 2 5 --title "Choose the reference" --menu "" 0 $width $num 2>&1 >/dev/tty)
        echo $selection
        selection=$(expr $selection - 1)
        refs=($references)
        clear
        get_query $(echo ${refs[$selection]} | cut -d "\"" -f 2)
        results=$(curl -s $query_url)
        show_results "$results"
    fi
}

process_args $@ && get_query $1 && {
    results=$(curl -s $query_url)
    show_results "$results"
}
