language: node_js
node_js:
  - "0.10"
before_install: 
  - npm install -g grunt-cli 
  - npm install -g jasmine-node
before_script:
  - psql -c 'create database slashdb;' -U postgres
  - psql -c 'CREATE USER slash WITH PASSWORD "slash1234";'
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE slashdb to slash;'
  - psql -d slashdb -a -f db/init.sql -U postgres
  - psql -d slashdb -a -f db/init_data.sql -U postgres